### ISSUE TITLE
[Feature] Rename extracted folders.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#18]
Mods are managed as: `author.modname`, so I think it would make sense to extract to folders named the same.

**Comment by AnActualEmerald** [comment]
So I've done some thinking on this, I'm not sure what the best way to go about it would be. Ideally mod authors should just package their mods in such a way that the folder that is extracted is already named that way. It would be easy to rename the folder after the fact but there are a lot of mods that extract into multiple folders, so that would need to be handled somehow but it isn't obvious to me what the best way to do that is.

**Comment by AnActualEmerald** [comment]
I think I've decided that this is an issue for mod authors to figure out. There's a format that their packages should follow and it shouldn't fall on package managers to correct that if they don't.
